!HighlandBagpipe.scl
!
Theoretical highland bagpipe scale
7
!
9/8
39/32
171/128
3/2
13/8
57/32
2/1
! Created with the iOS app "Wilsonic" by Marcus Hobbs
!
! Theoretical highland bagpipe scale based on the harmonics of the drones.
! (C) 1997 by McDonald Wilson
! A -> 32nd harmonic
! B -> 36th harmonic
! C= -> 39th harmonic
! D -> 171st harmonic
! E -> 48th harmonic
! F= -> 52nd harmonic
! G -> 57th harmonic

! Please see the Scala archives at: http://www.huygens-fokker.org/docs/scalesdir.txt
